{% set name = "python-int-nomax-str-digits" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 0
  string: {{ PKG_BUILDNUM }}_unix  # [unix]
  string: {{ PKG_BUILDNUM }}_win   # [win]

test:
  requires:
    - python *

about:
  home: https://github.com/conda-forge/python-int-nomax-str-digits-feedstock
  summary: 'An activation script that sets PYTHONINTMAXSTRDIGITS=0'
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
